### ISSUE TITLE
illegal Argument Exception: TestName cannot be null or empty

### ISSUE THREAD

**Issue by vpradeepkumar94** [sitture/cucumber-jvm-extentreport#13]
Please help in Resolving this error message.

java.lang.IllegalArgumentException: testName cannot be null or empty
	at com.aventstack.extentreports.ExtentTest.<init>(ExtentTest.java:80)
	at com.aventstack.extentreports.ExtentReports.createTest(ExtentReports.java:105)
	at com.aventstack.extentreports.ExtentReports.createTest(ExtentReports.java:145)
	at com.cucumber.listener.ExtentCucumberFormatter.feature(ExtentCucumberFormatter.java:94)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at cucumber.runtime.Utils$1.call(Utils.java:37)
	at cucumber.runtime.Timeout.timeout(Timeout.java:13)
	at cucumber.runtime.Utils.invoke(Utils.java:31)
	at cucumber.runtime.RuntimeOptions$1.invoke(RuntimeOptions.java:290)
	at com.sun.proxy.$Proxy26.feature(Unknown Source)
	at cucumber.runtime.model.CucumberFeature.run(CucumberFeature.java:161)
	at cucumber.api.testng.TestNGCucumberRunner.runCucumber(TestNGCucumberRunner.java:63)
	at cucumber.api.testng.AbstractTestNGCucumberTests.feature(AbstractTestNGCucumberTests.java:21)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:152)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:57)

I'm using  below jars
cucumber-extentreport-3.0.1jar
extentreport-3.0.7
jre-1.8

@AfterSuite
	public void tearDown() {
		 Reporter.loadXMLConfig(new
		 File("src/test/resources/extent-config.xml"));
		 Reporter.setSystemInfo("user", System.getProperty("user.name"));
		 Reporter.setSystemInfo("os", "Mac OSX");
		 Reporter.setTestRunnerOutput("Sample test runner output message");
		 System.out.println("came11");
	}
I'm not sure where I need to pass the parameter name

**Comment by haroon-sheikh** [comment]
Hi @vpradeepkumar94, I've just tried cucumber-jvm-extentreport v3.0.7 and cucumber v2.0.1 with on of your testng projects https://github.com/vpradeepkumar94/CucumberWithMavenHybridFrameWork and it seems to work as expected. 

Do you have an example project you can share to reproduce the problem?

**Comment by haroon-sheikh** [comment]
@anshooarora can you shed some light on this issue?

**Comment by vpradeepkumar94** [comment]
Hi,Thanks for reply,
It works fine for me,when I execute via pom.XML, (my github project)
But I have implemented the same framework  without using maven in another machine,
(Downloads jars separately)
that's where this issue comes for me,
Cucumberv -1.2.4 used
I can share that code sooner,if that might help u in anaylsing the reason for this issue.

**Comment by anshooarora** [comment]
This error is because the name of the test as in:

```
extent.createTest(testName);
```

The testName argument cannot be null or empty.

**Comment by haroon-sheikh** [comment]
Thanks @anshooarora 
@vpradeepkumar94 please use version 2.0.2 of the formatter if you’re using cucumber 1.2.4.

**Comment by vpradeepkumar94** [comment]
Hi @anshooarora 
do we need to mention this explicitly  "extent.createTest("SampleTest")" anywhere in the TestRunnerClass?

@RunWith(Cucumber.class)
@CucumberOptions(
        features = {"src/test/resources"},
        plugin = {"com.sitture.ExtentFormatter:output/extent-report/index.html", "html:output/html-report"})
public class RunCukesTest {
    @AfterClass
	public static void setup() {
        // Loads the extent config xml to customize on the report.
        ExtentReporter.setConfig("src/test/resources/config.xml");
        // adding system information
        ExtentReporter.setSystemInfo("Browser", "Chrome");
        ExtentReporter.setSystemInfo("Selenium", "v2.53.1");
	}
}

**Comment by haroon-sheikh** [comment]
No we dont need to @vpradeepkumar94.
Please share the full code to reproduce the issue?

**Comment by vpradeepkumar94** [comment]
Hi  @haroon-sheikh ,
I managed to find the root cause for this issue.

The above issue occurs,if the first line of the Feature Description is empty.

Example:
`Feature: Verify Application Home Page Title`
(The above code will not throw error but the below one throws)
Example:
`Feature: 

Verify Application Home Page Title`

**Comment by rajeeshnair** [comment]
hi @haroon-sheikh @anshooarora  is there anyway we can pass this featurename from config file or somewhere.Issue is am using export cucmber feature of Jira xray through pipeline.So when its export the feature file ,feature name shoudn't be there and test is failing with testName null. Could you please provide a remedy on this if possible soon.

**Comment by prabhus06** [comment]
@rajeeshnair - Have you managed to resolve the above mentioned issue. i am also facing the same issue with similar setup from XRAY
