### ISSUE TITLE
Latest version does not work with cucumber-jvm 2.1.0+

### ISSUE THREAD

**Issue by aukevanleeuwen** [sitture/cucumber-jvm-extentreport#15]
It throws the following stacktrace:

```
cucumber.runtime.CucumberException: java.lang.IllegalAccessError: tried to access class cucumber.runtime.formatter.TestSourcesModel from class com.sitture.ExtentFormatter
	at cucumber.runtime.formatter.PluginFactory.newInstance(PluginFactory.java:110)
	at cucumber.runtime.formatter.PluginFactory.instantiate(PluginFactory.java:91)
	at cucumber.runtime.formatter.PluginFactory.create(PluginFactory.java:76)
	at cucumber.runtime.RuntimeOptions.getPlugins(RuntimeOptions.java:323)
	at cucumber.runtime.RuntimeOptions.cucumberFeatures(RuntimeOptions.java:312)
	at cucumber.api.junit.Cucumber.<init>(Cucumber.java:66)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.junit.internal.builders.AnnotatedBuilder.buildRunner(AnnotatedBuilder.java:104)
	at org.junit.internal.builders.AnnotatedBuilder.runnerForClass(AnnotatedBuilder.java:86)
	at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:59)
	at org.junit.internal.builders.AllDefaultPossibilitiesBuilder.runnerForClass(AllDefaultPossibilitiesBuilder.java:26)
	at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:59)
	at org.junit.internal.requests.ClassRequest.getRunner(ClassRequest.java:33)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:250)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
Caused by: java.lang.IllegalAccessError: tried to access class cucumber.runtime.formatter.TestSourcesModel from class com.sitture.ExtentFormatter
	at com.sitture.ExtentFormatter.<init>(ExtentFormatter.java:53)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at cucumber.runtime.formatter.PluginFactory.newInstance(PluginFactory.java:104)
	... 27 more
```
Apparently in version 2.1.0, the visibility of this class was reduced. I'm commenting on their PR (cucumber/cucumber-jvm#1253) to see if this was the intention and what to do with formatters such as this one.

**Comment by haroon-sheikh** [comment]
@aukevanleeuwen thanks for investigating this. Shall we copy the missing class over?

**Comment by aukevanleeuwen** [comment]
For now that seems to be the easiest and quickest option, and it's not a huge class either. I'd say do it.

Sorry for the late reply.

**Comment by haroon-sheikh** [comment]
thats now done in `3.1.0`.
